Add exercise 7 files
GabrielPradoC/helpperOrigins pull request #12
Opened 2021-11-07 21:10 UTC by GabrielPradoC

2021-11-07 21:10 UTC, GabrielPradoC commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 7](https://trello.com/c/iZdfqiBh/204-exerc%C3%ADcio-7)

2021-11-10 01:10 UTC, matheus-yudi-helpper requested changes

2021-11-10 01:10 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/TableOutputHandler.ts
> +export class TableOutputHandler extends ProcessNumberArrayImperative{
Usar injeção de dependência. Você pode passar uma instância da classe NumberArray para poder trabalhar com os métodos dela.

2021-11-10 01:10 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/GenerateRandomUserTableData.ts
> +export class GenerateRandomUserTableData{
Criar uma classe para manipular o elemento tabela, nomear como `Table` ou algo do tipo, sempre um substantivo.

2021-11-10 01:10 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/ProcessNumberArrayFunctional.ts
> +export class ProcessNumberArrayFunctional{
Criar uma classe para manipular uma lista de números, nomear como `NumberArray` ou algo do tipo, sempre um substantivo.

2021-11-10 01:10 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/ProcessNumberArrayImperative.ts
> +    public getMinMedianMaxValues(): Array<number>{
Usar `average`.

2021-11-10 01:10 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/ProcessNumberArrayImperative.ts
> +            let medianValue: number = 0;
Usar `averageValue`.

2021-11-10 01:10 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/TableOutputHandler.ts
> +export class TableOutputHandler extends ProcessNumberArrayImperative{
Você pode até inclusive, se achar que faz sentido, incluir os métodos desta classe na classe `Table`.

2021-11-10 02:03 UTC, GabrielPradoC commented on sprint-2/src/Utils.ts
> +    public static appendElements(elementsArray: Array<HTMLElement>, rootElement: HTMLElement): void{
Código corrigido.

2021-11-10 02:07 UTC, GabrielPradoC commented on sprint-2/src/Utils.ts
> +            const firstChild = element.children[0] as HTMLElement;
Código corrigido.

2021-11-10 02:14 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/ProcessNumberArrayFunctional.ts
> +    private getMedianValue(): number{
Código corrigido.

2021-11-10 02:14 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/ProcessNumberArrayFunctional.ts
> +    public getMinMedianMaxValues(): Array<number>{
Código corrigido.

2021-11-10 02:14 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/ProcessNumberArrayFunctional.ts
> +            const medianValue: number = this.getMedianValue();
Código corrigido.

2021-11-10 02:20 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/ProcessNumberArrayImperative.ts
> +    public getMinMedianMaxValues(): Array<number>{
Código corrigido.

2021-11-10 02:20 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/ProcessNumberArrayImperative.ts
> +            let medianValue: number = 0;
Código corrigido.

2021-11-10 11:33 UTC, matheus-yudi-helpper commented
O que você pode fazer também é criar uma classe abstrata (NumberArray) com os métodos padrões usados tanto no `imperative` quanto no `functional` e a partir dela, extender as classes (NumberArrayFunctional) e (NumberArrayImperative).

2021-11-11 00:36 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/GenerateRandomUserTableData.ts
> +export class GenerateRandomUserTableData{
Código resolvido.

2021-11-11 00:42 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/TableOutputHandler.ts
> +export class TableOutputHandler extends ProcessNumberArrayImperative{
Código corrigido.

2021-11-11 00:42 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/ProcessNumberArrayFunctional.ts
> +export class ProcessNumberArrayFunctional{
Código corrigido.

2021-11-11 21:38 UTC, matheus-yudi-helpper requested changes

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +export class NumberArrayFunctional{
Adicionar o `implements INumberArray`.

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +        return Math.floor(this.numberArray.reduce(this.sumNumbers) / this.numberArray.length);
Incluir um valor alternativo caso o array seja vazio, se não, vai ocorrer divisão por 0. Você pode usar 

```ts
Math.floor(this.numberArray.reduce(this.sumNumbers) / (this.numberArray.length || 1))
```

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +    private getMinValue(): number{
Você poderia deixar esses métodos como públicos, também faria sentido já que manipula a lista.

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +    private getMaxValue(): number{
Você poderia deixar esses métodos como públicos, também faria sentido já que manipula a lista.

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/Types.ts
> +    generateRandomNumbersArray: (numberOfElements: number)=> void;
Você pode nomear o método como `generateRandom` apenas, pois como a classe leva o nome `NumberArray`, subentende-se que irá gerar uma array de numbers aleatórios. Da mesma forma que `Person.getName` e não `Person.getPersonName`, por exemplo.

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayImperative.ts
> +export class NumberArrayImperative{
Adicionar `implements INumberArray`

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayImperative.ts
> +            averageValue = Math.round(averageValue/this.numberArray.length);
Incluir um valor alternativo caso o array seja vazio, se não, vai ocorrer divisão por 0. Você pode usar 

```ts
Math.round(averageValue / (this.numberArray.length || 1))
```

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayImperative.ts
> +     public generateRandomNumbersArray(numberOfElements: number): void{
Deixar apenas como `generateRandom`.

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +    public generateRandomNumbersArray(numberOfElements: number): void{
Deixar apenas como `generateRandom`.

2021-11-11 21:38 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +        for(let i:number = 0; i< numberOfElements; i++){
Usar `index` em vez de apenas `i`.

2021-11-11 21:58 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +export class NumberArrayFunctional{
Código corrigido.

2021-11-11 22:00 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +        return Math.floor(this.numberArray.reduce(this.sumNumbers) / this.numberArray.length);
Código corrigido.

2021-11-11 22:00 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +    private getMinValue(): number{
Código corrigido.

2021-11-11 22:01 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +    private getMaxValue(): number{
Código corrigido.

2021-11-11 22:03 UTC, GabrielPradoC commented on sprint-2/src/Types.ts
> +    generateRandomNumbersArray: (numberOfElements: number)=> void;
Código corrigido.

2021-11-11 22:03 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayImperative.ts
> +export class NumberArrayImperative{
Código corrigido.

2021-11-11 22:05 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayImperative.ts
> +     public generateRandomNumbersArray(numberOfElements: number): void{
Código corrigido.

2021-11-11 22:05 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +    public generateRandomNumbersArray(numberOfElements: number): void{
Código corrigido.

2021-11-11 22:06 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayImperative.ts
> +            averageValue = Math.round(averageValue/this.numberArray.length);
Código corrigido.

2021-11-11 22:09 UTC, GabrielPradoC commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +        for(let i:number = 0; i< numberOfElements; i++){
Eu vou fazer a mudança porém faz mais sentido deixar como `iterator`.

2021-11-11 22:25 UTC, matheus-yudi-helpper approved these changes

2021-11-11 22:25 UTC, matheus-yudi-helpper commented on sprint-2/src/exercise7-classes/NumberArrayFunctional.ts
> +        }
Você poderia fazer desses jeitos legais também:

```ts
Array(numberOfElements).fill().map(() => Math.floor(Math.random() * 100));

Array.from({ length: numberOfElements }, () => Math.floor(Math.random() * 100));
```

2021-11-11 22:25 UTC, matheus-yudi-helpper commented
Corrige os conflitos antes de mergear :+1:

2021-11-12 00:03 UTC, merged